services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flask-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      FLASK_ENV: development
      BACKEND_URL: http://backend:5000
      FETCH_WEBSITE_URL: http://fetch_website:3001
      LLM_API_URL: http://trend_keywords:3002
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask-backend
    env_file:
      - ./.env
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: NextGenAI
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "5000:5000"
    volumes:
      - ./linkedin-agent-478216-f37f2b2ce601.json:/app/linkedin-agent-478216-f37f2b2ce601.json:ro
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: NextGenAI
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

  fetch_website:
    build:
      context: ./Fetch_Website
      dockerfile: Dockerfile
    container_name: fetch-website
    command: python fetch.py
    env_file:
      - ./.env
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      FIRECRAWL_API_KEY: ${FIRECRAWL_API_KEY}
    networks:
      - app-network
    restart: unless-stopped

  trend_keywords:
    build:
      context: ./trend_keywords
      dockerfile: Dockerfile
    container_name: trend-keywords
    command: python trends_keyword.py
    env_file:
      - ./.env
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FIRECRAWL_API_KEY: ${FIRECRAWL_API_KEY}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
